[build]
  functions = ".netlify/functions"
  command = "node build.js"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

# Additional security headers for payment processing
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://js.stripe.com; connect-src 'self' https://api.stripe.com; frame-src https://js.stripe.com; style-src 'self' 'unsafe-inline'"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"